In [3]:
!pip install scikit-learn

In [52]:
# Importing the required packages
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
  
# Function importing Dataset
def importdata():
    balance_data = pd.read_csv("dibetic_data.txt", header = None)

    """
    balance_data = pd.read_csv(
'https://archive.ics.uci.edu/ml/machine-learning-'+
'databases/balance-scale/balance-scale.data',
    sep= ',', header = None)   
    """

    # Printing the dataswet shape
    print ("Dataset Length: ", len(balance_data))
    print ("Dataset Shape: ", balance_data.shape)
      
    # Printing the dataset obseravtions
    print ("Dataset: ",balance_data.head())
    return balance_data

def tarin_using_entropy(X_train, X_test, y_train):
  
    # Decision tree with entropy
    clf_entropy = DecisionTreeClassifier(
            criterion = "entropy", random_state = 100,
            max_depth = 3, min_samples_leaf = 1)
  
    # Performing training
    clf_entropy.fit(X_train, y_train)
    return clf_entropy

# Function to make predictions
def prediction(X_test, clf_object):
  
    # Predicton on test with giniIndex
    y_pred = clf_object.predict(X_test)
    print("Predicted values:")
    print(y_pred)
    return y_pred

# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
      
    print("Confusion Matrix: ",
        confusion_matrix(y_test, y_pred))
      
    print ("Accuracy : ",
    accuracy_score(y_test,y_pred)*100)
      
    print("Report : ",
    classification_report(y_test, y_pred))

# Function to split the dataset
def splitdataset(balance_data):
  
    # Separating the target variable
    X = balance_data.values[:, 0:3]
    Y = balance_data.values[:, 3]
    #X = balance_data.values[:, 1:5]
    #Y = balance_data.values[:, 0] 

    # Splitting the dataset into train and test
    X_train, X_test, y_train, y_test = train_test_split( 
    X, Y, test_size = 0.3, random_state = 100)
      
    return X, Y, X_train, X_test, y_train, y_test

def main():
      
    # Building Phase
    data = importdata()
    X, Y, X_train, X_test, y_train, y_test = splitdataset(data)
    
    clf_entropy = tarin_using_entropy(X_train, X_test, y_train)
      
    print("X_train:\n {}".format(X_train))
    print("X_test:\n {}".format(X_test))
    print("y_test:\n {}".format(y_test))

    print("Results Using Entropy:")
    # Prediction using entropy
    y_pred_entropy = prediction(X_test, clf_entropy)
    cal_accuracy(y_test, y_pred_entropy)


# Calling main function
if __name__=="__main__":
    main()

Dataset Length:  10
Dataset Shape:  (10, 4)
Dataset:     0  1     2  3
0  0  1  2.54  0
1  1  0  1.31  0
2  1  1  1.13  0
3  0  0  2.07  0
4  1  1  2.34  1
X_train:
 [[1.   0.   0.55]
 [1.   1.   2.34]
 [1.   1.   1.13]
 [0.   1.   2.54]
 [0.   0.   2.07]
 [1.   1.   8.29]
 [1.   0.   1.14]]
X_test:
 [[1.   1.   3.12]
 [0.   1.   2.48]
 [1.   0.   1.31]]
y_test:
 [1. 0. 0.]
Results Using Entropy:
Predicted values:
[1. 0. 0.]
Confusion Matrix:  [[2 0]
 [0 1]]
Accuracy :  100.0
Report :                precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         2
         1.0       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3

